# Generated by Django 4.0.3 on 2023-10-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_remove_appointment_date_time_appointment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='purchased_here',
            field=models.BooleanField(default=False),
        ),
    ]
